# This module implements functions to create and parse paths for model data.

# Input data is following a structure that contains a list of traditional weather
# model identifiers:

# - `<model_name>`: Name of the model
# - `<model_config>`: Name of the model configuration
# - `<bbox>`: Bounding box of the model
# - `<resolution>`: Resolution of the model
# - `<analysis_time>`: Analysis time of the model run in [ISO8601
#   format](https://en.wikipedia.org/wiki/ISO_8601) (without colons ":" which is
#   still valid ISO8601 format)
# - `<data_kind>`: Kind of data [e.g. "pressure_levels", "surface_levels"]

# A path is then constructed as follows:
# ```
# <model_name>/<model_config>/<bbox>/<resolution>/<analysis_time>/<data_kind>.zarr
# ```
# - `<model_name>` is a string that contains the name of the model, e.g.
#   `harmonie_cy46`, `ifs_cy50`, etc.
# - `<bbox>` is a string that contains the coordinates of the bounding box in the
#   format `w<lon_min>_s<lat_min>_e<lon_max>_n<lat_max>`.
# - `<resolution>` is a string that contains the resolution of the model in the
#   format `dx<lon_resolution><unit>_dy<lat_resolution><unit>`.

# All floats (`lon_min`, `lat_min`, `lon_max`, `lat_max`, `lon_resolution`,
# `lat_resolution`) are formatted with 'p' in place of the decimal point to avoid
# having dots in the paths. For example, `dx0.1` becomes `dx0p1`.

inputs:
  # - uri: s3://forecast-data-public/harmonie/dini/w0p1_s50p0_e10p0_n60p0/dx2p5km_dy2p5km/{analysis_time}/pressure_levels.zarr
  #   internal_path: /volume/data/pressure_levels.zarr
  # - uri: s3://forecast-data-private/ifs/cy50/w0p1_s50p0_e10p0_n60p0/dx2p5km_dy2p5km/{analysis_time}/pressure_levels.zarr
  #   internal_path: /volume/data/pressure_levels.zarr
  dini_pressure_levels:
    uri_args:
      bbox:
        lon_min: -10.0
        lat_min: 50.0
        lon_max: 10.0
        lat_max: 60.0
      resolution:
        lon_resolution: 2.5
        lat_resolution: 2.5
        units: km
      data_kind: pressure_levels
      model_name: harmonie_cy46
      model_config: dini
      bucket_name: forecast-data-public
    internal_path: /volume/inputs/dini/pressure_levels.zarr
  ifs_pressure_levels:
    uri_args:
      bbox:
        lon_min: -12.0
        lat_min: 48.0
        lon_max: 12.0
        lat_max: 62.0
      resolution:
        lon_resolution: 1.0
        lat_resolution: 1.0
        units: deg
      data_kind: pressure_levels
      model_name: ifs_cy50
      model_config: FakeIFS
      bucket_name: forecast-data-private
    internal_path: /volume/inputs/ifs/pressure_levels.zarr

outputs:
  - internal_path: /volume/output/pressure_levels.zarr
    uri_args:
      bbox:
        lon_min: -10.0
        lat_min: 50.0
        lon_max: 10.0
        lat_max: 60.0
      resolution:
        lon_resolution: 2.5
        lat_resolution: 2.5
        units: km
      data_kind: pressure_levels
      model_name: gefion1
      model_config: FakeDINI+FakeIFS
      bucket_name: forecast-data-public
